/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class Pendaftaran extends javax.swing.JFrame {

    public Pendaftaran() {
        initComponents();
    }
    Kontroll kon = new Kontroll();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nama_pengguna = new javax.swing.JTextField();
        Konfirmasi_sandi = new javax.swing.JPasswordField();
        Nama_perusahaan = new javax.swing.JTextField();
        Kata_sandi = new javax.swing.JPasswordField();
        Pemberitahuan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nama_pengguna.setBorder(null);
        Nama_pengguna.setOpaque(false);
        getContentPane().add(Nama_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 279, 460, 32));

        Konfirmasi_sandi.setBorder(null);
        Konfirmasi_sandi.setOpaque(false);
        Konfirmasi_sandi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Konfirmasi_sandiKeyReleased(evt);
            }
        });
        getContentPane().add(Konfirmasi_sandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 406, 460, 32));

        Nama_perusahaan.setBorder(null);
        Nama_perusahaan.setOpaque(false);
        getContentPane().add(Nama_perusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 216, 460, 32));

        Kata_sandi.setBorder(null);
        Kata_sandi.setOpaque(false);
        getContentPane().add(Kata_sandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 342, 460, 32));

        Pemberitahuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Pemberitahuan.setForeground(new java.awt.Color(195, 0, 0));
        getContentPane().add(Pemberitahuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 240, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 470, 255, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi/Pendaftaran.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1141, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        String nama_perusahaan = Nama_perusahaan.getText();
        String nama_pengguna = Nama_pengguna.getText();
        String pass = new String(Konfirmasi_sandi.getPassword());
        Pengguna p = new Pengguna();
        if (!nama_pengguna.equals("")||!nama_perusahaan.equals("")||!pass.equals("")) {
            p.setUser(nama_pengguna);
            p.setPassword(pass);
            p.setNama_Perusahaan(nama_perusahaan);
            int i = kon.simpan(p);
            if (i==1) {
                new Login().setVisible(true);
                this.dispose();
            } else {
            reset_pass();
        }
        } else {
            JOptionPane.showMessageDialog(null, "Tolong isi semua datanya", "Pesan", 1);
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void Konfirmasi_sandiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Konfirmasi_sandiKeyReleased
        // TODO add your handling code here:
        String kata=  new String(Kata_sandi.getPassword());
        String cek =  new String(Konfirmasi_sandi.getPassword());
        if (cek.equals("")) {
            Pemberitahuan.setText(null);
        }else if (!kata.equals(cek)) {
            Pemberitahuan.setText("Sepertinya kata sandimu tidak cocok");
        }else if (kata.equals(cek)) {
            Pemberitahuan.setText(null);
        }
    }//GEN-LAST:event_Konfirmasi_sandiKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pendaftaran().setVisible(true);
            }
        });
    }
    
    public void reset_pass(){
        Kata_sandi.setText(null);
        Konfirmasi_sandi.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Kata_sandi;
    private javax.swing.JPasswordField Konfirmasi_sandi;
    private javax.swing.JTextField Nama_pengguna;
    private javax.swing.JTextField Nama_perusahaan;
    private javax.swing.JLabel Pemberitahuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
